### ISSUE TITLE
Dynamic backend

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#116]
## output format
A json list of objects that represent a node in the taxonomy tree. Each object has 3 keys: 

- `long`: name of the taxonomy node
- `short`: shortened (unique) name
- `parent`: reference to parent's `short`

```
[
    { 
        long: "Test execution", 
        short: "execution", 
        parent: "scope" 
    },
    { 
        long: "Solving new problem", 
        short: "solving", 
        parent: "effect" 
    },
    ...
]
```

Maybe it's a good idea to change `long` and `short` to `name` and `id`, respectively?

## internal schema
Collection taxonomy is stored as a json file. The base serp taxonomy is read from some json file and kept in memory.

There are only two actions possible: `read` and `write`. To guard against nasty race conditions and out-of-date writes we will use versioning. Each `read` will return the version id, and each successful `write` will increase it. A version id must be included in the `write` request and must be >= than the current value, otherwise the request is denied.

## modifications
`/collection/{id}/add-entry` must now clone the entry.

`/collection/{id}/remove-entry` must now delete the entry.

A new endpoint `/collection/{id}/taxonomy` must be added for `GET` and `PUT`.

A new endpoint `/collection/{id}/classify` must be added for reclassification of entities.

**Comment by smeets** [comment]
It is now implemented
