### ISSUE TITLE
Substitute taxonomy relations with tags

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#16]
Syntax: `#tag: <entity text>`

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Substitute taxonomy relations with tags](https://trello.com/c/hksBxSLV/16-substitute-taxonomy-relations-with-tags)

**Comment by emenlu** [comment]
How to guide the user?

**Comment by smeets** [comment]
We closed this for frontend, so I'm closing this one here as well
