### ISSUE TITLE
create test framework

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#17]
Allow devs to test their features/behavior of the backend

**Comment by emenlu** [comment]
It could be useful to add comments to explain the rationale of added test cases.

**Comment by smeets** [comment]
Current test framework (explained [here](https://github.com/emenlu/connect/wiki/Testing))
- `mvn verify` / integration test phase
- included neo4j community edition server
- `pippo-test` module
- `URLParser` and `Mailbox` classes to interface with emails
- circle ci for continuous testing of commits and pull requests
  - passes coverage results to codecov
