### ISSUE TITLE
Reset password via form instead of emailing a new password

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#19]
Instead of sending the password in an email, allow user to choose her password (wisely).

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#19 Reset password via form instead of emailing a new password](https://trello.com/c/WTMooI5k/29-19-reset-password-via-form-instead-of-emailing-a-new-password)

**Comment by smeets** [comment]
MUST HAVE TEST CASE
