### ISSUE TITLE
Detail session management

### ISSUE THREAD

**Issue by smeets** [serpconnect/backend#22]
Wiki page on session management, e.g what pippo implicitly does for us and what we must explicitly do.
- A session is mainly a cookie (`JSESSIONID`) that has some data on the server
- Data on server is so far only "email" _or_ "resetemail" - used for authentication
- Server uses in-memory session store (sessions are destroyed on reboot/update)

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#22 Detail session management](https://trello.com/c/OXiAQcwE/31-22-detail-session-management)
