### ISSUE TITLE
Detail trust levels

### ISSUE THREAD

**Issue by smeets** [serpconnect/backend#23]
Info on what the different types of trust are, how they can be changed, how they are represented, etc.
- Internally as an int between 0-inf
- Higher is better (more trust)
- Levels
  - Admin 9999
  - Verified 999
  - User 99
  - Registered 9
  - Unregistered 1
  - (banned 0) ?
- Only admins may change trust level

Explicit, automatic trust changes:
- Unregistered ⇒ Registered
  - User registers on website and can log in.
- Registered ⇒ User
  - Registered users must prove they own their email used during registration by clicking on the verify link inside a registration email sent during signup

Admin can set trust level of any other user (including other admins).

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#23 Detail trust levels](https://trello.com/c/q16M4Y0g/33-23-detail-trust-levels)
