### ISSUE TITLE
Ephermeral database for testing

### ISSUE THREAD

**Issue by smeets** [serpconnect/backend#25]
Testing will require an ephemeral/impermanent database.

Solutions
- use an embedded neo4j for testing
  - each test case has its own db? one for all?
- manage database from command line
  - start a neo4j test server from the mvn task
  - one for all test cases

**Comment by smeets** [comment]
http://fooo.fr/~vjeux/github/github-recommandation/db/doc/manual/html/server-embedded.html

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#25 Ephermeral database for testing](https://trello.com/c/bISLRuPb/35-25-ephermeral-database-for-testing)

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test plan](https://trello.com/c/PliFWTxJ/1-test-plan)
