### ISSUE TITLE
Testable mailman

### ISSUE THREAD

**Issue by smeets** [serpconnect/backend#26]
Instead of a static class, `Mailman`, make it an interface to enable devs to write their own implementations, mainly for separating testing, development and production (special) cases. 

Example:
- test mode: collects email, verify message, extract content, ...
- dev/prod: send email

**Comment by emenlu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#26 Testable mailman](https://trello.com/c/472WSeXk/36-26-testable-mailman)
