### ISSUE TITLE
Delete collections that have no members

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#6]

**Comment by smeets** [comment]
At the moment it is only possible to leave a collection (delete is not available), and only from the collection page (reachable from the profile page by clicking 'manage'). If this is ok we can close this.

**Comment by emenlu** [comment]
If everyone leaves a collection I think it should be deleted.

**Comment by emenlu** [comment]
True, we solved that before summer. Where/how should the user get information on how to do it?

**Comment by emenlu** [comment]
Is there a test case? (system level)
