### ISSUE TITLE
Make 10k ft. overview image of backend

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#68]

**Comment by smeets** [comment]
Currently doing this using http://www.graphviz.org/. Looks like this atm:

![overview](https://cloud.githubusercontent.com/assets/6011225/22423737/4d8eb40c-e6f3-11e6-8d2c-5509258a8343.png)

**Comment by smeets** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make 10k ft. overview image of backend](https://trello.com/c/JLFaBujp/119-make-10k-ft-overview-image-of-backend)
