### ISSUE TITLE
(collection) Implement collection membership levels

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#78]
There are 3 levels of membership: _owner_, _member_, _observer_.

The creator of the collection is assigned _owner_ status. Invited members are assigned _member_ status. An _observer_ is someone who isn't related to the collection at all (e.g. russian hacker).

We could impl. this in neo4j using relations:

 - owner: `(u)-[:owner]->(c)`
 - member: `(u)-[:member_of]->(c)`

This might impact some endpoints that depend on `:member_of`.

**Comment by smeets** [comment]
Included in #89
