### ISSUE TITLE
Server profiling

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#82]

**Comment by smeets** [comment]
Preliminary tests show that it's probably jcypher that's slow.

Some numbers:
 - `Account.findByEmail`: ~250ms
 - `post /entry/new`: ~600ms

`Database.query` is (for us) the single most expensive call we can do. The cost seems to be hidden in java-to-request translation and checking the cache (LRU).

Trace: `/entry/new` ->  `jcypher` ->  `network` -> `neo4j`

According to cypher command `PROFILE`, `Account.findByEmail` should be about ~60ms from the browser playground, so we seem be a incurring a huge overhead by using jcypher.

**Comment by smeets** [comment]
This information has been added to the documentation so I'm closing this issue
